apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: godzilla
  name: godzilla
  namespace: test-chaos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: godzilla
  template:
    metadata:
      labels:
        app: godzilla
    spec:
      dnsPolicy: ClusterFirst
      serviceAccountName: chaos-admin
      containers:
        - command:
            - ./godzilla
          image: wxt432/godzilla-chaos:latest
          stdin: true
          tty: true
          imagePullPolicy: Always
          name: godzilla
          env:
            - name: JOB_NAMESPACE
              value: test-chaos
            - name: GODZILLA_MYSQL_HOST
              value: mysql
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: chaos-admin
  namespace: test-chaos
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chaos-admin-role
rules:
  - verbs:
      - '*'
    apiGroups:
      - '*'
    resources:
      - '*'
  - verbs:
      - '*'
    nonResourceURLs:
      - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chaos-admin-rb
subjects:
  - kind: ServiceAccount
    name: chaos-admin
    namespace: test-chaos
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chaos-admin-role
---
kind: Service
apiVersion: v1
metadata:
  name: godzilla
  namespace: test-chaos
spec:
  selector:
    app: godzilla
  ports:
    - name: godzilla
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
