kind: ServiceAccount
apiVersion: v1
metadata:
  name: chaos-admin
  labels:
    name: chaos-admin
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chaos-admin
  labels:
    name: chaos-admin
subjects:
  - kind: ServiceAccount
    name: chaos-admin
    namespace: chaos-gjcdi0cp6sl77aj1 # todo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chaos-admin
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chaos-admin
  labels:
    name: chaos-admin
rules:
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - deletecollection
    apiGroups:
      - ''
    resources:
      - pods
      - events
  - verbs:
      - get
      - list
    apiGroups:
      - ''
    resources:
      - secrets
      - configmaps
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - pods/log
  - verbs:
      - create
      - list
      - get
      - delete
      - deletecollection
    apiGroups:
      - batch
    resources:
      - jobs
  - verbs:
      - create
      - delete
      - deletecollection
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - deletecollection
    apiGroups:
      - ''
    resources:
      - events
  - verbs:
      - get
      - list
      - patch
      - update
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - get
      - list
      - create
    apiGroups:
      - ''
    resources:
      - pods/exec
      - pods/eviction
      - replicationcontrollers
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - pods/log
  - verbs:
      - create
      - delete
      - get
      - list
      - delete
      - deletecollection
    apiGroups:
      - ''
    resources:
      - services
  - verbs:
      - list
      - get
      - patch
      - update
    apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
  - verbs:
      - list
      - get
    apiGroups:
      - apps
    resources:
      - replicasets
  - verbs:
      - list
      - get
      - delete
    apiGroups:
      - apps
    resources:
      - daemonsets
  - verbs:
      - list
      - get
    apiGroups:
      - apps.openshift.io
    resources:
      - deploymentconfigs
  - verbs:
      - list
      - get
    apiGroups:
      - argoproj.io
    resources:
      - rollouts
  - verbs:
      - create
      - list
      - get
      - patch
      - update
      - delete
    apiGroups:
      - litmuschaos.io
    resources:
      - chaosengines
      - chaosexperiments
      - chaosresults
  - verbs:
      - patch
      - get
      - list
      - update
    apiGroups:
      - ''
    resources:
      - nodes
